### ISSUE TITLE
- Show whether a text was sent or not

### ISSUE THREAD

**Issue by dunkeltron** [AccelerateNetworks/fusionpbx-webtexting#55] opened 2024-03-26 20:00 UTC

**Comment by uncheckederror** [comment] 2024-09-04 21:06
This appear to be a duplicate of the work in #1.

**Closed by uncheckederror** 2024-09-04 21:06 UTC

**Comment by dunkeltron** [comment] 2025-12-29 22:36
We can now tell when a message has successfully been sent upstream. We relay this information to the user as a circle with a checkmark one their outbound message once the outbound message has been confirmed to ahve been sent upstream.
